name: CI Pipeline

on:
  workflow_call: 
    inputs:
      code-checkout-and-setup:
        required: false
        default: true
        type: boolean
      Codeql-analysis:
        required: false
        default: false
        type: boolean
      sonarqube:
        required: false
        default: false
        type: boolean
      build:
        required: false
        default: true
        type: boolean
    secrets:
      SONAR_TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  code-checkout-and-setup:
    if: ${{ inputs.code-checkout-and-setup }}
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6.0.0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: pip install -r requirements.txt

      - name: Run Tests
        run: |
          mkdir -p test-results/
          pytest --cov=. --cov-report=xml:test-results/coverage.xml --junitxml=test-results/test-results.xml

      - name: Upload Test artifacts
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: test-results/
  
  Codeql-analysis:
    if: ${{ inputs.Codeql-analysis }}
    runs-on: ubuntu-latest
    needs: code-checkout-and-setup
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0
       
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: 'Security'

  sonarqube:
    if: ${{ inputs.sonarqube }}
    runs-on: ubuntu-latest
    needs: code-checkout-and-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      - name: Download coverage report
        uses: actions/download-artifact@v7
        with:
          name: test-results
          path: test-results/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    if: ${{ success() && inputs.build }}
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [code-checkout-and-setup, Codeql-analysis, sonarqube]
    outputs:
      image_tags: ${{ steps.vars.outputs.IMAGE_TAGS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Generate Docker image tags
        id: vars
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
          echo "IMAGE_TAGS=$IMAGE_TAGS" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:${{ steps.vars.outputs.IMAGE_TAGS }}
          push: True
          load: true
